### ISSUE TITLE
Potted plant

### ISSUE THREAD

**Issue by ChillyCyanide** [nnichael/MOGL#126] opened 2022-06-11 18:21 UTC
**List your installed mods**

- none

**How you triggered the behavior**

- Placing potted plant if there are more than 1 in a sfack

**What you expected would happen**

- One of the pots to be placed

**What actually happened**

- placed  1 but but it takes the whole stack

**Comment by nnichael** [comment] 2022-06-11 18:40
Thanks! 👀 dupe of #113

**Closed by nnichael** 2022-06-11 18:40 UTC
Labels: bug
