### ISSUE TITLE
shipment boat missing blocks

### ISSUE THREAD

**Issue by Pumpkin-Headington** [nnichael/MOGL#42] opened 2021-11-01 19:43 UTC
**list your installed mods**

- none

**how you triggered the behavior**

- log into mogl
- look at shipment boat

**what you expected would happen**

- ship doesn't have exposed area

**what actually happened**

- ship has exposed area on the port (left) side

**logs and screenshots**
<img width="1134" alt="Screen Shot 2021-10-31 at 1 26 06 PM" src="https://user-images.githubusercontent.com/92835506/139731535-746e782c-474e-4b61-84f4-2ae2eb8fc6df.png">

**Comment by nnichael** [comment] 2022-05-25 23:55
Unfortunately, this is working as intended. Will close this for now.

**Closed by nnichael** 2022-05-25 23:55 UTC
Labels: bug
